/**
 * PATCH 8.1 — Commercial Search Analytics taxonomies
 */

export const MIA_COMMERCIAL_SEARCH_CATALOG_VERSION = "8.1.0";

export const MIA_COMMERCIAL_SEARCH_RUNTIME_MODES = Object.freeze({
  LEGACY: "LEGACY",
  CONTROLLED: "CONTROLLED",
  SHADOW: "SHADOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_COMMERCIAL_SEARCH_INTENT_TYPES = Object.freeze({
  COMMERCIAL: "COMMERCIAL",
  MIXED: "MIXED",
});

export const MIA_COMMERCIAL_SEARCH_QUERY_EXTRACTION_STATUSES = Object.freeze({
  NOT_REQUIRED: "NOT_REQUIRED",
  SUCCESS: "SUCCESS",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
});

export const MIA_COMMERCIAL_SEARCH_QUERY_CHANGE_TYPES = Object.freeze({
  NONE: "NONE",
  EXTRACTION: "EXTRACTION",
  NORMALIZATION: "NORMALIZATION",
  EXTRACTION_AND_NORMALIZATION: "EXTRACTION_AND_NORMALIZATION",
});

export const MIA_COMMERCIAL_SEARCH_GATE_STATUSES = Object.freeze({
  PASSED: "PASSED",
  BLOCKED: "BLOCKED",
  BYPASSED: "BYPASSED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_COMMERCIAL_SEARCH_EXECUTION_STATUSES = Object.freeze({
  EXECUTED: "EXECUTED",
  NOT_EXECUTED: "NOT_EXECUTED",
  ABORTED: "ABORTED",
  FAILED: "FAILED",
});

export const MIA_COMMERCIAL_SEARCH_PATHS = Object.freeze({
  DATA_LAYER_ONLY: "DATA_LAYER_ONLY",
  DATA_LAYER_THEN_PROVIDER: "DATA_LAYER_THEN_PROVIDER",
  PROVIDER_ONLY: "PROVIDER_ONLY",
  NO_SEARCH: "NO_SEARCH",
  UNKNOWN: "UNKNOWN",
});

export const MIA_COMMERCIAL_SEARCH_RESULT_STATUSES = Object.freeze({
  RESULTS_FOUND: "RESULTS_FOUND",
  PARTIAL_RESULTS: "PARTIAL_RESULTS",
  NO_RESULTS: "NO_RESULTS",
  FALLBACK_RESULT: "FALLBACK_RESULT",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_COMMERCIAL_SEARCH_TERMINATION_STAGES = Object.freeze({
  COMMERCIAL_GATE: "COMMERCIAL_GATE",
  QUERY_EXTRACTION: "QUERY_EXTRACTION",
  DATA_LAYER: "DATA_LAYER",
  PROVIDER_ROUTER: "PROVIDER_ROUTER",
  RANKING: "RANKING",
  OFFER_PIPELINE: "OFFER_PIPELINE",
  RESPONSE_BUILDER: "RESPONSE_BUILDER",
  UNKNOWN: "UNKNOWN",
});
