/**
 * PATCH 8.3 — Offer Set Analytics taxonomies
 */

export const MIA_OFFER_SET_CATALOG_VERSION = "8.3.0";

export const MIA_OFFER_PIPELINE_STATUSES = Object.freeze({
  SUCCESS: "SUCCESS",
  PARTIAL: "PARTIAL",
  EMPTY: "EMPTY",
  FAILED: "FAILED",
  NOT_EXECUTED: "NOT_EXECUTED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_OFFER_TERMINATION_STAGES = Object.freeze({
  RAW: "RAW",
  NORMALIZATION: "NORMALIZATION",
  MERGE: "MERGE",
  DEDUP: "DEDUP",
  RANKING: "RANKING",
  SELECTION: "SELECTION",
  DELIVERY: "DELIVERY",
  UNKNOWN: "UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

/** Maps from PATCH 8.1 search paths for offer-set reporting */
export const MIA_OFFER_SET_SEARCH_PATHS = Object.freeze({
  DATA_LAYER_ONLY: "DATA_LAYER_ONLY",
  PROVIDER_ONLY: "PROVIDER_ONLY",
  HYBRID: "HYBRID",
  FALLBACK: "FALLBACK",
  UNKNOWN: "UNKNOWN",
});

export const MIA_OFFER_SET_RUNTIME_MODES = Object.freeze({
  LEGACY: "LEGACY",
  CONTROLLED: "CONTROLLED",
  SHADOW: "SHADOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_OFFER_SET_DEFAULT_CURRENCY = "BRL";
