/**
 * PATCH 10.3 — Price Alert Lifecycle taxonomies (observational only).
 */

export const MIA_PRICE_ALERT_LIFECYCLE_CATALOG_VERSION = "10.3.0";

export const MIA_ALERT_LIFECYCLE_STAGE = Object.freeze({
  REQUESTED: "REQUESTED",
  CREATED: "CREATED",
  ACTIVE: "ACTIVE",
  CHECKED: "CHECKED",
  TARGET_REACHED: "TARGET_REACHED",
  NOTIFICATION_PREPARED: "NOTIFICATION_PREPARED",
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  NOTIFICATION_DELIVERED: "NOTIFICATION_DELIVERED",
  NOTIFICATION_FAILED: "NOTIFICATION_FAILED",
  USER_RETURNED: "USER_RETURNED",
  OFFER_OPENED: "OFFER_OPENED",
  PAUSED: "PAUSED",
  REACTIVATED: "REACTIVATED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  FAILED: "FAILED",
  UNKNOWN: "UNKNOWN",
});

/** Reserved — not emitted until architecture supports them */
export const MIA_ALERT_LIFECYCLE_RESERVED = Object.freeze([
  MIA_ALERT_LIFECYCLE_STAGE.NOTIFICATION_DELIVERED,
  MIA_ALERT_LIFECYCLE_STAGE.USER_RETURNED,
  MIA_ALERT_LIFECYCLE_STAGE.OFFER_OPENED,
  MIA_ALERT_LIFECYCLE_STAGE.PAUSED,
  MIA_ALERT_LIFECYCLE_STAGE.REACTIVATED,
  MIA_ALERT_LIFECYCLE_STAGE.CANCELLED,
  MIA_ALERT_LIFECYCLE_STAGE.EXPIRED,
]);

export const MIA_ALERT_STATUS = Object.freeze({
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  FAILED: "FAILED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_SOURCE = Object.freeze({
  MIA_RECOMMENDATION: "MIA_RECOMMENDATION",
  OFFER_CARD: "OFFER_CARD",
  FAVORITE: "FAVORITE",
  PRODUCT_PAGE: "PRODUCT_PAGE",
  PRICE_ALERT_PAGE: "PRICE_ALERT_PAGE",
  CONVERSATION: "CONVERSATION",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_CREATION_FAILURE_REASON = Object.freeze({
  INVALID_CURRENT_PRICE: "INVALID_CURRENT_PRICE",
  INVALID_TARGET_PRICE: "INVALID_TARGET_PRICE",
  TARGET_NOT_BELOW_CURRENT_PRICE: "TARGET_NOT_BELOW_CURRENT_PRICE",
  MISSING_PRODUCT_REFERENCE: "MISSING_PRODUCT_REFERENCE",
  MISSING_USER_REFERENCE: "MISSING_USER_REFERENCE",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  DUPLICATE_ALERT: "DUPLICATE_ALERT",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_TARGET_REALISM = Object.freeze({
  TARGET_ALREADY_REACHED: "TARGET_ALREADY_REACHED",
  TARGET_NEAR_CURRENT: "TARGET_NEAR_CURRENT",
  TARGET_MODERATE: "TARGET_MODERATE",
  TARGET_AGGRESSIVE: "TARGET_AGGRESSIVE",
  TARGET_EXTREME: "TARGET_EXTREME",
  INVALID: "INVALID",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_CHECK_FAILURE_REASON = Object.freeze({
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  INVALID_PRICE: "INVALID_PRICE",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  RATE_LIMITED: "RATE_LIMITED",
  TIMEOUT: "TIMEOUT",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_FAILURE_STAGE = Object.freeze({
  CREATION: "CREATION",
  PERSISTENCE: "PERSISTENCE",
  PRICE_CHECK: "PRICE_CHECK",
  PROVIDER: "PROVIDER",
  COMPARISON: "COMPARISON",
  NOTIFICATION: "NOTIFICATION",
  CORRELATION: "CORRELATION",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALERT_OFFICIAL_CURRENCY = "BRL";

/** Target realism thresholds (percent below current) */
export const MIA_TARGET_NEAR_MAX_PERCENT = 2;
export const MIA_TARGET_MODERATE_MAX_PERCENT = 10;
export const MIA_TARGET_AGGRESSIVE_MAX_PERCENT = 25;
