/**
 * PATCH 9.4 — Runner-up and alternative analytics taxonomies (derived layer).
 */

export const MIA_RECOMMENDATION_ALTERNATIVE_CATALOG_VERSION = "9.4.0";

/** Cognitive runner-up authority source */
export const MIA_RUNNER_UP_SOURCES = Object.freeze({
  RANKED_PRODUCTS_SCAN: "RANKED_PRODUCTS_SCAN",
  UNAVAILABLE: "UNAVAILABLE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SCORE_GAP_BUCKETS = Object.freeze({
  TIE: "TIE",
  VERY_CLOSE: "VERY_CLOSE",
  CLOSE: "CLOSE",
  MODERATE: "MODERATE",
  WIDE: "WIDE",
  UNKNOWN: "UNKNOWN",
});

/** Limits documented for decision-score scale (PATCH 9.1 observed range) */
export const MIA_SCORE_GAP_VERY_CLOSE_MAX = 2;
export const MIA_SCORE_GAP_CLOSE_MAX = 5;
export const MIA_SCORE_GAP_MODERATE_MAX = 10;

export const MIA_RUNNER_UP_COMPETITIVENESS = Object.freeze({
  EQUIVALENT: "EQUIVALENT",
  HIGHLY_COMPETITIVE: "HIGHLY_COMPETITIVE",
  COMPETITIVE: "COMPETITIVE",
  DISTANT: "DISTANT",
  NOT_COMPARABLE: "NOT_COMPARABLE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALTERNATIVE_MATCH_METHODS = Object.freeze({
  EXACT_FAMILY_MATCH: "EXACT_FAMILY_MATCH",
  SAFE_PRODUCT_ID_MATCH: "SAFE_PRODUCT_ID_MATCH",
  OFFER_TO_PRODUCT_MATCH: "OFFER_TO_PRODUCT_MATCH",
  PROVIDER_CATEGORY_MATCH: "PROVIDER_CATEGORY_MATCH",
  PARTIAL_MATCH: "PARTIAL_MATCH",
  NO_MATCH: "NO_MATCH",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_ALTERNATIVE_MATCH_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_ALTERNATIVE_RELATIONSHIPS = Object.freeze({
  COGNITIVE_RUNNER_UP: "COGNITIVE_RUNNER_UP",
  DISPLAYED_RUNNER_UP: "DISPLAYED_RUNNER_UP",
  DISPLAYED_ALTERNATIVE: "DISPLAYED_ALTERNATIVE",
  OFFER_ALTERNATIVE: "OFFER_ALTERNATIVE",
  REQUESTED_ALTERNATIVE: "REQUESTED_ALTERNATIVE",
  SELECTED_RUNNER_UP: "SELECTED_RUNNER_UP",
  SELECTED_ALTERNATIVE: "SELECTED_ALTERNATIVE",
  REPLACEMENT_WINNER: "REPLACEMENT_WINNER",
  NON_RUNNER_UP_REPLACEMENT: "NON_RUNNER_UP_REPLACEMENT",
  UNRESOLVED_ALTERNATIVE: "UNRESOLVED_ALTERNATIVE",
  NO_ALTERNATIVE: "NO_ALTERNATIVE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALTERNATIVE_OUTCOMES = Object.freeze({
  RUNNER_UP_NOT_AVAILABLE: "RUNNER_UP_NOT_AVAILABLE",
  RUNNER_UP_AVAILABLE_NOT_DISPLAYED: "RUNNER_UP_AVAILABLE_NOT_DISPLAYED",
  RUNNER_UP_DISPLAYED_NO_SIGNAL: "RUNNER_UP_DISPLAYED_NO_SIGNAL",
  RUNNER_UP_INTERACTION: "RUNNER_UP_INTERACTION",
  RUNNER_UP_SELECTED: "RUNNER_UP_SELECTED",
  RUNNER_UP_REPLACED_WINNER: "RUNNER_UP_REPLACED_WINNER",
  ALTERNATIVE_REQUESTED_ONLY: "ALTERNATIVE_REQUESTED_ONLY",
  ALTERNATIVE_INTERACTION: "ALTERNATIVE_INTERACTION",
  ALTERNATIVE_SELECTED: "ALTERNATIVE_SELECTED",
  ALTERNATIVE_RECOVERED_FLOW: "ALTERNATIVE_RECOVERED_FLOW",
  ALTERNATIVE_FAILED_TO_RECOVER: "ALTERNATIVE_FAILED_TO_RECOVER",
  DECISION_RETAINED: "DECISION_RETAINED",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_ALTERNATIVE_RECOVERY_CLASSES = Object.freeze({
  RECOVERED_BY_RUNNER_UP: "RECOVERED_BY_RUNNER_UP",
  RECOVERED_BY_OTHER_ALTERNATIVE: "RECOVERED_BY_OTHER_ALTERNATIVE",
  RECOVERED_BY_NEW_SEARCH: "RECOVERED_BY_NEW_SEARCH",
  NOT_RECOVERED: "NOT_RECOVERED",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_ALTERNATIVE_DIVERSITY_CLASSES = Object.freeze({
  SAME_FAMILY_VARIANT: "SAME_FAMILY_VARIANT",
  SAME_BRAND_DIFFERENT_FAMILY: "SAME_BRAND_DIFFERENT_FAMILY",
  DIFFERENT_BRAND_SAME_CATEGORY: "DIFFERENT_BRAND_SAME_CATEGORY",
  DIFFERENT_PRICE_TIER: "DIFFERENT_PRICE_TIER",
  DIFFERENT_FEATURE_PROFILE: "DIFFERENT_FEATURE_PROFILE",
  OFFER_ONLY: "OFFER_ONLY",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ALTERNATIVE_EVIDENCE_LEVELS = Object.freeze({
  INTEREST_SIGNAL: "INTEREST_SIGNAL",
  STRONG_INTEREST_SIGNAL: "STRONG_INTEREST_SIGNAL",
  REPLACEMENT_DECISION: "REPLACEMENT_DECISION",
  CONFIRMED_SELECTION: "CONFIRMED_SELECTION",
  UNRESOLVED: "UNRESOLVED",
});
