/**
 * PATCH 10.5 — User Value Outcome taxonomies (observational only).
 *
 * Separates potential, observed, and verified value — never conflates them.
 */

export const MIA_USER_VALUE_OUTCOME_CATALOG_VERSION = "10.5.0";

/** Value layer categories (semantic grouping) */
export const MIA_VALUE_LAYER = Object.freeze({
  POTENTIAL_VALUE: "POTENTIAL_VALUE",
  OBSERVED_VALUE: "OBSERVED_VALUE",
  VERIFIED_VALUE: "VERIFIED_VALUE",
  UNKNOWN_VALUE: "UNKNOWN_VALUE",
});

/** Outcome status — never auto-convert OBSERVED → VERIFIED */
export const MIA_VALUE_OUTCOME_STATUS = Object.freeze({
  POTENTIAL: "POTENTIAL",
  OBSERVED: "OBSERVED",
  VERIFIED: "VERIFIED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_VALUE_TYPE = Object.freeze({
  PRICE_OPPORTUNITY: "PRICE_OPPORTUNITY",
  PRICE_DROP: "PRICE_DROP",
  TIME_SAVED: "TIME_SAVED",
  DECISION_SUPPORT: "DECISION_SUPPORT",
  ALERT_SUCCESS: "ALERT_SUCCESS",
  PRODUCT_DISCOVERY: "PRODUCT_DISCOVERY",
  CONFIDENCE_GAIN: "CONFIDENCE_GAIN",
  UNKNOWN: "UNKNOWN",
});

export const MIA_VALUE_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_VALUE_EVIDENCE = Object.freeze({
  PRICE_INTELLIGENCE: "PRICE_INTELLIGENCE",
  SAVINGS_ESTIMATION: "SAVINGS_ESTIMATION",
  ALERT_TARGET_REACHED: "ALERT_TARGET_REACHED",
  ALERT_LIFECYCLE: "ALERT_LIFECYCLE",
  ACCEPTANCE_SIGNAL: "ACCEPTANCE_SIGNAL",
  REJECTION_SIGNAL: "REJECTION_SIGNAL",
  RUNNER_UP: "RUNNER_UP",
  FAVORITE: "FAVORITE",
  OFFER_CLICK: "OFFER_CLICK",
  PRICE_ALERT: "PRICE_ALERT",
  ANTI_REGRET: "ANTI_REGRET",
  DECISION_CONTEXT: "DECISION_CONTEXT",
  UNKNOWN: "UNKNOWN",
});

export const MIA_VALUE_COMPONENT = Object.freeze({
  PRICE: "PRICE",
  SAVINGS: "SAVINGS",
  ALERTS: "ALERTS",
  DECISION: "DECISION",
  FAVORITES: "FAVORITES",
  OFFER_CLICKS: "OFFER_CLICKS",
  ANTI_REGRET: "ANTI_REGRET",
  CONFIDENCE: "CONFIDENCE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_TIME_SAVED_BUCKET = Object.freeze({
  VERY_LOW: "VERY_LOW",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  UNKNOWN: "UNKNOWN",
});

export const MIA_USER_VALUE_SCORE_MIN = 0;
export const MIA_USER_VALUE_SCORE_MAX = 100;
export const MIA_USER_VALUE_SCORE_NEUTRAL_BASE = 40;

/** Documented component weights (sum used for normalization, not ranking) */
export const MIA_VALUE_COMPONENT_WEIGHTS = Object.freeze({
  [MIA_VALUE_COMPONENT.PRICE]: 15,
  [MIA_VALUE_COMPONENT.SAVINGS]: 20,
  [MIA_VALUE_COMPONENT.ALERTS]: 15,
  [MIA_VALUE_COMPONENT.DECISION]: 10,
  [MIA_VALUE_COMPONENT.FAVORITES]: 8,
  [MIA_VALUE_COMPONENT.OFFER_CLICKS]: 8,
  [MIA_VALUE_COMPONENT.ANTI_REGRET]: 12,
  [MIA_VALUE_COMPONENT.CONFIDENCE]: 7,
});

export const MIA_VERIFIED_VALUE_UNAVAILABLE = "NOT_AVAILABLE";
